/*
 * Order Service G09
 * API designed by team G09 for the HS24 SWDA course at HSLU
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ch.hslu.swda.model;

import java.util.Objects;
import java.util.Arrays;
import ch.hslu.swda.model.Address;
import ch.hslu.swda.model.ContactInfo;
import com.fasterxml.jackson.annotation.*;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import io.micronaut.core.annotation.*;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CustomerCreate
 */
@JsonPropertyOrder({
  CustomerCreate.JSON_PROPERTY_FIRST_NAME,
  CustomerCreate.JSON_PROPERTY_FAMILY_NAME,
  CustomerCreate.JSON_PROPERTY_ADDRESS,
  CustomerCreate.JSON_PROPERTY_CONTACT_INFO
})
@JsonTypeName("CustomerCreate")
@Introspected
public class CustomerCreate {
    public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
    private String firstName;

    public static final String JSON_PROPERTY_FAMILY_NAME = "familyName";
    private String familyName;

    public static final String JSON_PROPERTY_ADDRESS = "address";
    private Address address;

    public static final String JSON_PROPERTY_CONTACT_INFO = "contactInfo";
    private ContactInfo contactInfo;

    public CustomerCreate(String firstName, String familyName, Address address, ContactInfo contactInfo) {
        this.firstName = firstName;
        this.familyName = familyName;
        this.address = address;
        this.contactInfo = contactInfo;
    }

    public CustomerCreate() {}

    public CustomerCreate firstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Get firstName
     * @return firstName
     */
    @NotNull
    @Schema(name = "firstName", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_FIRST_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getFirstName() {
        return firstName;
    }

    @JsonProperty(JSON_PROPERTY_FIRST_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public CustomerCreate familyName(String familyName) {
        this.familyName = familyName;
        return this;
    }

    /**
     * Get familyName
     * @return familyName
     */
    @NotNull
    @Schema(name = "familyName", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_FAMILY_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getFamilyName() {
        return familyName;
    }

    @JsonProperty(JSON_PROPERTY_FAMILY_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setFamilyName(String familyName) {
        this.familyName = familyName;
    }

    public CustomerCreate address(Address address) {
        this.address = address;
        return this;
    }

    /**
     * Get address
     * @return address
     */
    @Valid
    @NotNull
    @Schema(name = "address", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Address getAddress() {
        return address;
    }

    @JsonProperty(JSON_PROPERTY_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setAddress(Address address) {
        this.address = address;
    }

    public CustomerCreate contactInfo(ContactInfo contactInfo) {
        this.contactInfo = contactInfo;
        return this;
    }

    /**
     * Get contactInfo
     * @return contactInfo
     */
    @Valid
    @NotNull
    @Schema(name = "contactInfo", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_CONTACT_INFO)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public ContactInfo getContactInfo() {
        return contactInfo;
    }

    @JsonProperty(JSON_PROPERTY_CONTACT_INFO)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setContactInfo(ContactInfo contactInfo) {
        this.contactInfo = contactInfo;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CustomerCreate customerCreate = (CustomerCreate) o;
        return Objects.equals(this.firstName, customerCreate.firstName) &&
                Objects.equals(this.familyName, customerCreate.familyName) &&
                Objects.equals(this.address, customerCreate.address) &&
                Objects.equals(this.contactInfo, customerCreate.contactInfo);
    }

    @Override
    public int hashCode() {
        return Objects.hash(firstName, familyName, address, contactInfo);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CustomerCreate {\n");
        sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
        sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
        sb.append("    address: ").append(toIndentedString(address)).append("\n");
        sb.append("    contactInfo: ").append(toIndentedString(contactInfo)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

