/*
 * Order Service G09
 * API designed by team G09 for the HS24 SWDA course at HSLU
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ch.hslu.swda.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.serde.annotation.Serdeable;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Schema for updating order items
 */
@Serdeable
@Schema(name = "OrderUpdate", description = "Schema for updating order")
@JsonPropertyOrder({
        OrderUpdate.JSON_PROPERTY_ORDER_ITEMS,
})
@Introspected
public class OrderUpdate {

    public static final String JSON_PROPERTY_ORDER_ITEMS = "orderItems";
    private List<@Valid OrderItemCreate> orderItems = null;
    private Order.StatusEnum status = null;

    public OrderUpdate() {
    }

    public OrderUpdate orderItems(List<@Valid OrderItemCreate> orderItems) {
        this.orderItems = orderItems;
        return this;
    }

    public OrderUpdate addOrderItemsItem(OrderItemCreate orderItemsItem) {
        if (this.orderItems == null) {
            this.orderItems = new ArrayList<>();
        }
        this.orderItems.add(orderItemsItem);
        return this;
    }

    @Schema(name = "orderItems", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_ORDER_ITEMS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<@Valid OrderItemCreate> getOrderItems() {
        return orderItems;
    }

    @JsonProperty(JSON_PROPERTY_ORDER_ITEMS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOrderItems(List<@Valid OrderItemCreate> orderItems) {
        this.orderItems = orderItems;
    }

    public OrderUpdate status(Order.StatusEnum status) {
        this.status = status;
        return this;
    }

    @Schema(name = "status", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("status")
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Order.StatusEnum getStatus() {
        return status;
    }

    @JsonProperty("status")
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStatus(Order.StatusEnum status) {
        this.status = status;
    }

    @Override
    public final boolean equals(Object object) {
        if (object == this) {
            return true;
        }
        return (object instanceof OrderUpdate that)
                && Objects.equals(that.orderItems, this.orderItems);
    }

    @Override
    public final int hashCode() {
        return Objects.hash(orderItems);
    }

    @Override
    public String toString() {
        return "OrderUpdate [" +
                "orderItems=" + orderItems +
                ']';
    }
}

