/*
 * Order Service G09
 * API designed by team G09 for the HS24 SWDA course at HSLU
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ch.hslu.swda.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.serde.annotation.Serdeable;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
import java.util.UUID;

/**
 * Schema for updating the status of an order
 */
@Serdeable
@Schema(name = "OrderStatusUpdate", description = "Schema for updating the status of an order")
@JsonPropertyOrder({
        OrderStatusUpdate.JSON_PROPERTY_ORDER_ID,
        OrderStatusUpdate.JSON_PROPERTY_ORDER_STATUS,
})

@Introspected
public class OrderStatusUpdate {

    public static final String JSON_PROPERTY_ORDER_ID = "orderId";
    public static final String JSON_PROPERTY_ORDER_STATUS = "status";
    private UUID orderId = null;
    private Order.StatusEnum status = null;

    public OrderStatusUpdate(UUID orderId, Order.StatusEnum status) {
        this.orderId = orderId;
        this.status = status;
    }

    public OrderStatusUpdate() {
        this(null, null);
    }

    public OrderStatusUpdate orderId(UUID orderId) {
        this.orderId = orderId;
        return this;
    }

    @Schema(name = "orderId", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_ORDER_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UUID getOrderId() {
        return this.orderId;
    }

    @JsonProperty(JSON_PROPERTY_ORDER_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setOrderId(UUID orderId) {
        this.orderId = orderId;
    }

    public OrderStatusUpdate status(Order.StatusEnum status) {
        this.status = status;
        return this;
    }

    @Schema(name = "status", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_ORDER_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Order.StatusEnum getStatus() {
        return this.status;
    }

    @JsonProperty(JSON_PROPERTY_ORDER_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStatus(Order.StatusEnum status) {
        this.status = status;
    }

    @Override
    public final boolean equals(Object object) {
        if (object == this) {
            return true;
        }
        return (object instanceof OrderStatusUpdate that)
                &&
                Objects.equals(that.orderId, this.orderId)
                && status == that.status;
    }

    @Override
    public final int hashCode() {
        return Objects.hash(orderId, status);
    }

    @Override
    public String toString() {
        return "OrderStatusUpdate [" +
                "orderId=" + this.orderId + ", " +
                "status=" + this.status + ']';
    }
}

