/*
 * Order Service G09
 * API designed by team G09 for the HS24 SWDA course at HSLU
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ch.hslu.swda.model;

import com.fasterxml.jackson.annotation.*;
import io.micronaut.core.annotation.Introspected;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * CustomerOrder
 */
@JsonPropertyOrder({
  CustomerOrder.JSON_PROPERTY_ID,
  CustomerOrder.JSON_PROPERTY_DATE_TIME,
  CustomerOrder.JSON_PROPERTY_STATUS,
  CustomerOrder.JSON_PROPERTY_ORDER_ITEMS,
  CustomerOrder.JSON_PROPERTY_PRICE,
  CustomerOrder.JSON_PROPERTY_ORDER_TYPE,
  CustomerOrder.JSON_PROPERTY_CUSTOMER,
  CustomerOrder.JSON_PROPERTY_SELLER
})
@JsonTypeName("CustomerOrder")
@Introspected
public class CustomerOrder extends Order {
    public static final String JSON_PROPERTY_ID = "id";
    private UUID id;

    public static final String JSON_PROPERTY_DATE_TIME = "dateTime";
    private OffsetDateTime dateTime;

    /**
     * Gets or Sets status
     */
    public enum StatusEnum {
        UNVALIDATED("UNVALIDATED"),
        PENDING("PENDING"),
        CONFIRMED("CONFIRMED"),
        AWAITING_PAYMENT("AWAITING_PAYMENT"),
        DONE("DONE");

        private String value;

        StatusEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static StatusEnum fromValue(String value) {
            for (StatusEnum b : StatusEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public static final String JSON_PROPERTY_STATUS = "status";
    private Order.StatusEnum status;

    public static final String JSON_PROPERTY_ORDER_ITEMS = "orderItems";
    private List<@Valid OrderItem> orderItems = new ArrayList<>();

    public static final String JSON_PROPERTY_PRICE = "price";
    private BigDecimal price;

    /**
     * Gets or Sets orderType
     */
    public enum OrderTypeEnum {
        CUSTOMER_ORDER("CUSTOMER_ORDER");

        private String value;

        OrderTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static OrderTypeEnum fromValue(String value) {
            for (OrderTypeEnum b : OrderTypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public static final String JSON_PROPERTY_ORDER_TYPE = "orderType";
    private Order.OrderTypeEnum orderType;

    public static final String JSON_PROPERTY_CUSTOMER = "customer";
    private Customer customer;

    public static final String JSON_PROPERTY_SELLER = "seller";
    private Employee seller;

    public CustomerOrder(UUID id, OffsetDateTime dateTime, Order.StatusEnum status, List<@Valid OrderItem> orderItems, BigDecimal price, Order.OrderTypeEnum orderType, Customer customer, Employee seller) {
        super(orderType);
        this.id = id;
        this.dateTime = dateTime;
        this.status = status;
        this.orderItems = orderItems;
        this.price = price;
        this.orderType = orderType;
        this.customer = customer;
        this.seller = seller;
    }

    public CustomerOrder id(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     */
    @NotNull
    @Schema(name = "id", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UUID getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setId(UUID id) {
        this.id = id;
    }

    public CustomerOrder dateTime(OffsetDateTime dateTime) {
        this.dateTime = dateTime;
        return this;
    }

    /**
     * Get dateTime
     * @return dateTime
     */
    @NotNull
    @Schema(name = "dateTime", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_DATE_TIME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public OffsetDateTime getDateTime() {
        return dateTime;
    }

    @JsonProperty(JSON_PROPERTY_DATE_TIME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public void setDateTime(OffsetDateTime dateTime) {
        this.dateTime = dateTime;
    }

    public CustomerOrder status(Order.StatusEnum status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     */
    @Schema(name = "status", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Order.@NotNull StatusEnum getStatus() {
        return status;
    }

    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setStatus(Order.StatusEnum status) {
        this.status = status;
    }

    public CustomerOrder orderItems(List<@Valid OrderItem> orderItems) {
        this.orderItems = orderItems;
        return this;
    }

    public CustomerOrder addOrderItemsItem(OrderItem orderItemsItem) {
        this.orderItems.add(orderItemsItem);
        return this;
    }

    /**
     * Get orderItems
     * @return orderItems
     */
    @NotNull
    @Schema(name = "orderItems", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_ORDER_ITEMS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public List<@Valid OrderItem> getOrderItems() {
        return orderItems;
    }

    @JsonProperty(JSON_PROPERTY_ORDER_ITEMS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setOrderItems(List<@Valid OrderItem> orderItems) {
        this.orderItems = orderItems;
    }

    public CustomerOrder price(BigDecimal price) {
        this.price = price;
        return this;
    }

    /**
     * Get price
     * @return price
     */
    @NotNull
    @Schema(name = "price", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_PRICE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public BigDecimal getPrice() {
        return price;
    }

    @JsonProperty(JSON_PROPERTY_PRICE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public CustomerOrder orderType(Order.OrderTypeEnum orderType) {
        this.orderType = orderType;
        return this;
    }

    /**
     * Get orderType
     * @return orderType
     */
    @NotNull
    @Schema(name = "orderType", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Order.OrderTypeEnum getOrderType() {
        return orderType;
    }

    @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setOrderType(Order.OrderTypeEnum orderType) {
        this.orderType = orderType;
    }

    public CustomerOrder customer(Customer customer) {
        this.customer = customer;
        return this;
    }

    /**
     * Get customer
     * @return customer
     */
    @Valid
    @NotNull
    @Schema(name = "customer", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_CUSTOMER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Customer getCustomer() {
        return customer;
    }

    @JsonProperty(JSON_PROPERTY_CUSTOMER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public CustomerOrder seller(Employee seller) {
        this.seller = seller;
        return this;
    }

    /**
     * Get seller
     * @return seller
     */
    @Valid
    @NotNull
    @Schema(name = "seller", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_SELLER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Employee getSeller() {
        return seller;
    }

    @JsonProperty(JSON_PROPERTY_SELLER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setSeller(Employee seller) {
        this.seller = seller;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CustomerOrder customerOrder = (CustomerOrder) o;
        return Objects.equals(this.id, customerOrder.id) &&
            Objects.equals(this.dateTime, customerOrder.dateTime) &&
            Objects.equals(this.status, customerOrder.status) &&
            Objects.equals(this.orderItems, customerOrder.orderItems) &&
            Objects.equals(this.price, customerOrder.price) &&
            Objects.equals(this.orderType, customerOrder.orderType) &&
            Objects.equals(this.customer, customerOrder.customer) &&
            Objects.equals(this.seller, customerOrder.seller);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, dateTime, status, orderItems, price, orderType, customer, seller);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CustomerOrder {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    dateTime: ").append(toIndentedString(dateTime)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    orderItems: ").append(toIndentedString(orderItems)).append("\n");
        sb.append("    price: ").append(toIndentedString(price)).append("\n");
        sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
        sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
        sb.append("    seller: ").append(toIndentedString(seller)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

