/*
 * Order Service G09
 * API designed by team G09 for the HS24 SWDA course at HSLU
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ch.hslu.swda.model;

import com.fasterxml.jackson.annotation.*;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * CustomerOrderUpdate
 */
@JsonPropertyOrder({
  CustomerOrderUpdate.JSON_PROPERTY_DATE_TIME,
  CustomerOrderUpdate.JSON_PROPERTY_STATUS,
  CustomerOrderUpdate.JSON_PROPERTY_ORDER_ITEMS,
  CustomerOrderUpdate.JSON_PROPERTY_ORDER_TYPE,
  CustomerOrderUpdate.JSON_PROPERTY_CUSTOMER_ID,
  CustomerOrderUpdate.JSON_PROPERTY_SELLER_ID
})
@JsonTypeName("CustomerOrderUpdate")
@Introspected
public class CustomerOrderUpdate {
    public static final String JSON_PROPERTY_DATE_TIME = "dateTime";
    private OffsetDateTime dateTime;

    /**
     * Gets or Sets status
     */
    public enum StatusEnum {
        PENDING("PENDING"),
        CONFIRMED("CONFIRMED"),
        AWAITING_PAYMENT("AWAITING_PAYMENT"),
        DONE("DONE");

        private String value;

        StatusEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static StatusEnum fromValue(String value) {
            for (StatusEnum b : StatusEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public static final String JSON_PROPERTY_STATUS = "status";
    private StatusEnum status;

    public static final String JSON_PROPERTY_ORDER_ITEMS = "orderItems";
    private List<@Valid OrderItemCreate> orderItems = null;

    /**
     * Gets or Sets orderType
     */
    public enum OrderTypeEnum {
        CUSTOMER_ORDER("customerOrder");

        private String value;

        OrderTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static OrderTypeEnum fromValue(String value) {
            for (OrderTypeEnum b : OrderTypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public static final String JSON_PROPERTY_ORDER_TYPE = "orderType";
    private OrderTypeEnum orderType;

    public static final String JSON_PROPERTY_CUSTOMER_ID = "customerId";
    private UUID customerId;

    public static final String JSON_PROPERTY_SELLER_ID = "sellerId";
    private UUID sellerId;

    public CustomerOrderUpdate(OrderTypeEnum orderType) {
        this.orderType = orderType;
    }

    public CustomerOrderUpdate dateTime(OffsetDateTime dateTime) {
        this.dateTime = dateTime;
        return this;
    }

    /**
     * Get dateTime
     * @return dateTime
     */
    @Nullable
    @Schema(name = "dateTime", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_DATE_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public OffsetDateTime getDateTime() {
        return dateTime;
    }

    @JsonProperty(JSON_PROPERTY_DATE_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public void setDateTime(OffsetDateTime dateTime) {
        this.dateTime = dateTime;
    }

    public CustomerOrderUpdate status(StatusEnum status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     * @return status
     */
    @Nullable
    @Schema(name = "status", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public StatusEnum getStatus() {
        return status;
    }

    @JsonProperty(JSON_PROPERTY_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStatus(StatusEnum status) {
        this.status = status;
    }

    public CustomerOrderUpdate orderItems(List<@Valid OrderItemCreate> orderItems) {
        this.orderItems = orderItems;
        return this;
    }

    public CustomerOrderUpdate addOrderItemsItem(OrderItemCreate orderItemsItem) {
        if (this.orderItems == null) {
            this.orderItems = new ArrayList<>();
        }
        this.orderItems.add(orderItemsItem);
        return this;
    }

    /**
     * Get orderItems
     * @return orderItems
     */
    @Nullable
    @Schema(name = "orderItems", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_ORDER_ITEMS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<@Valid OrderItemCreate> getOrderItems() {
        return orderItems;
    }

    @JsonProperty(JSON_PROPERTY_ORDER_ITEMS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOrderItems(List<@Valid OrderItemCreate> orderItems) {
        this.orderItems = orderItems;
    }

    public CustomerOrderUpdate orderType(OrderTypeEnum orderType) {
        this.orderType = orderType;
        return this;
    }

    /**
     * Get orderType
     * @return orderType
     */
    @NotNull
    @Schema(name = "orderType", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public OrderTypeEnum getOrderType() {
        return orderType;
    }

    @JsonProperty(JSON_PROPERTY_ORDER_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setOrderType(OrderTypeEnum orderType) {
        this.orderType = orderType;
    }

    public CustomerOrderUpdate customerId(UUID customerId) {
        this.customerId = customerId;
        return this;
    }

    /**
     * Get customerId
     * @return customerId
     */
    @Nullable
    @Schema(name = "customerId", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public UUID getCustomerId() {
        return customerId;
    }

    @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCustomerId(UUID customerId) {
        this.customerId = customerId;
    }

    public CustomerOrderUpdate sellerId(UUID sellerId) {
        this.sellerId = sellerId;
        return this;
    }

    /**
     * Get sellerId
     * @return sellerId
     */
    @Nullable
    @Schema(name = "sellerId", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_SELLER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public UUID getSellerId() {
        return sellerId;
    }

    @JsonProperty(JSON_PROPERTY_SELLER_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSellerId(UUID sellerId) {
        this.sellerId = sellerId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CustomerOrderUpdate customerOrderUpdate = (CustomerOrderUpdate) o;
        return Objects.equals(this.dateTime, customerOrderUpdate.dateTime) &&
            Objects.equals(this.status, customerOrderUpdate.status) &&
            Objects.equals(this.orderItems, customerOrderUpdate.orderItems) &&
            Objects.equals(this.orderType, customerOrderUpdate.orderType) &&
            Objects.equals(this.customerId, customerOrderUpdate.customerId) &&
            Objects.equals(this.sellerId, customerOrderUpdate.sellerId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(dateTime, status, orderItems, orderType, customerId, sellerId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CustomerOrderUpdate {\n");
        sb.append("    dateTime: ").append(toIndentedString(dateTime)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    orderItems: ").append(toIndentedString(orderItems)).append("\n");
        sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
        sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
        sb.append("    sellerId: ").append(toIndentedString(sellerId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

