/*
 * Order Service G09
 * API designed by team G09 for the HS24 SWDA course at HSLU
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ch.hslu.swda.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.micronaut.core.annotation.Introspected;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;

import java.util.Objects;
import java.util.UUID;

/**
 * OrderItemCreate
 */
@JsonPropertyOrder({
  OrderItemCreate.JSON_PROPERTY_PRODUCT_ID,
  OrderItemCreate.JSON_PROPERTY_QUANTITY
})
@JsonTypeName("OrderItemCreate")
@Introspected
public class OrderItemCreate {
    public static final String JSON_PROPERTY_PRODUCT_ID = "productId";
    private UUID productId;

    public static final String JSON_PROPERTY_QUANTITY = "quantity";
    private Integer quantity;

    public OrderItemCreate(UUID productId, Integer quantity) {
        this.productId = productId;
        this.quantity = quantity;
    }

    public OrderItemCreate productId(UUID productId) {
        this.productId = productId;
        return this;
    }

    /**
     * Get productId
     * @return productId
     */
    @NotNull
    @Schema(name = "productId", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UUID getProductId() {
        return productId;
    }

    @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setProductId(UUID productId) {
        this.productId = productId;
    }

    public OrderItemCreate quantity(Integer quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Get quantity
     * @return quantity
     */
    @NotNull
    @Schema(name = "quantity", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_QUANTITY)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getQuantity() {
        return quantity;
    }

    @JsonProperty(JSON_PROPERTY_QUANTITY)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrderItemCreate orderItemCreate = (OrderItemCreate) o;
        return Objects.equals(this.productId, orderItemCreate.productId) &&
            Objects.equals(this.quantity, orderItemCreate.quantity);
    }

    @Override
    public int hashCode() {
        return Objects.hash(productId, quantity);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OrderItemCreate {\n");
        sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
        sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

