include:
  - project: hslu/shared/devops/cicd
    ref: v5-stable
    file:
      - edu/swarm.cd.yml
      - edu/config/swda.yml

  - project: hslu/edu/bachelor-computer-science/swda/shared/swda-ci
    ref: main
    file:
      - swda/config/config.yml

build:
  extends:
    - .job
    - .filterBuild
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/

