/*
 * Order Service G09
 * API designed by team G09 for the HS24 SWDA course at HSLU
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ch.hslu.swda.common.entities;

import com.fasterxml.jackson.annotation.*;
import io.micronaut.core.annotation.Introspected;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.bson.types.ObjectId;

import java.util.Objects;
import java.util.UUID;

/**
 * Customer
 */
@JsonPropertyOrder({
        Customer.JSON_PROPERTY_ID,
        Customer.JSON_PROPERTY_FIRST_NAME,
        Customer.JSON_PROPERTY_FAMILY_NAME,
        Customer.JSON_PROPERTY_ADDRESS,
        Customer.JSON_PROPERTY_CONTACT_INFO
})
@JsonTypeName("Customer")
@Introspected
public class Customer {
    public static final String JSON_PROPERTY_ID = "customerId";
    private UUID customerId;

    public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
    private String firstName;

    public static final String JSON_PROPERTY_FAMILY_NAME = "familyName";
    private String familyName;

    public static final String JSON_PROPERTY_ADDRESS = "address";
    private Address address;

    public static final String JSON_PROPERTY_CONTACT_INFO = "contactInfo";
    private ContactInfo contactInfo;

    private ObjectId id;

    public Customer(UUID customerId, String firstName, String familyName, Address address, ContactInfo contactInfo, ObjectId id) {
        this.customerId = customerId;
        this.firstName = firstName;
        this.familyName = familyName;
        this.address = address;
        this.contactInfo = contactInfo;
        this.id = id;
    }

    public Customer() {}

    public Customer id(UUID id) {
        this.customerId = id;
        return this;
    }

    /**
     * Get id
     * @return id
     */
    @NotNull
    @Schema(name = "customerId", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UUID getCustomerId() {
        return customerId;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setCustomerId(UUID customerId) {
        this.customerId = customerId;
    }

    public Customer firstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Get firstName
     * @return firstName
     */
    @NotNull
    @Schema(name = "firstName", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_FIRST_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getFirstName() {
        return firstName;
    }

    @JsonProperty(JSON_PROPERTY_FIRST_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public Customer familyName(String familyName) {
        this.familyName = familyName;
        return this;
    }

    /**
     * Get familyName
     * @return familyName
     */
    @NotNull
    @Schema(name = "familyName", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_FAMILY_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getFamilyName() {
        return familyName;
    }

    @JsonProperty(JSON_PROPERTY_FAMILY_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setFamilyName(String familyName) {
        this.familyName = familyName;
    }

    public Customer address(Address address) {
        this.address = address;
        return this;
    }

    /**
     * Get address
     * @return address
     */
    @Valid
    @NotNull
    @Schema(name = "address", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Address getAddress() {
        return address;
    }

    @JsonProperty(JSON_PROPERTY_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setAddress(Address address) {
        this.address = address;
    }

    public Customer contactInfo(ContactInfo contactInfo) {
        this.contactInfo = contactInfo;
        return this;
    }

    /**
     * Get contactInfo
     * @return contactInfo
     */
    @Valid
    @NotNull
    @Schema(name = "contactInfo", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_CONTACT_INFO)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public ContactInfo getContactInfo() {
        return contactInfo;
    }

    @JsonProperty(JSON_PROPERTY_CONTACT_INFO)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setContactInfo(ContactInfo contactInfo) {
        this.contactInfo = contactInfo;
    }

    @JsonIgnore
    public ObjectId getId() {
        return this.id;
    }

    public void setId(ObjectId id) {
        this.id = id;
    }

    public Customer id(ObjectId id) {
        this.id = id;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Customer customer = (Customer) o;
        return Objects.equals(this.customerId, customer.customerId) &&
                Objects.equals(this.firstName, customer.firstName) &&
                Objects.equals(this.familyName, customer.familyName) &&
                Objects.equals(this.address, customer.address) &&
                Objects.equals(this.contactInfo, customer.contactInfo) &&
                Objects.equals(this.id, customer.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(customerId, firstName, familyName, address, contactInfo, id);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Customer {\n");
        sb.append("    id: ").append(toIndentedString(customerId)).append("\n");
        sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
        sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
        sb.append("    address: ").append(toIndentedString(address)).append("\n");
        sb.append("    contactInfo: ").append(toIndentedString(contactInfo)).append("\n");
        sb.append("    objectId: ").append(toIndentedString(id)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

