/*
 * Order Service G09
 * API designed by team G09 for the HS24 SWDA course at HSLU
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ch.hslu.swda.common.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.micronaut.core.annotation.Introspected;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Schema for updating order items
 */
@Schema(name = "OrderItemUpdate", description = "Schema for updating order items")
@JsonPropertyOrder({
        OrderItemUpdate.JSON_PROPERTY_ORDER_ITEM_CREATE,
})

@Introspected
public class OrderItemUpdate {

    public static final String JSON_PROPERTY_ORDER_ITEM_CREATE = "orderItems";
    private List<@Valid OrderItemCreate> orderItems = null;

    public OrderItemUpdate() {
    }

    public OrderItemUpdate orderItems(List<@Valid OrderItemCreate> orderItems) {
        this.orderItems = orderItems;
        return this;
    }

    public OrderItemUpdate addOrderItemsItem(OrderItemCreate orderItemsItem) {
        if (this.orderItems == null) {
            this.orderItems = new ArrayList<>();
        }
        this.orderItems.add(orderItemsItem);
        return this;
    }

    @Schema(name = "orderItems", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_ORDER_ITEM_CREATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<@Valid OrderItemCreate> getOrderItems() {
        return orderItems;
    }

    @JsonProperty(JSON_PROPERTY_ORDER_ITEM_CREATE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOrderItems(List<@Valid OrderItemCreate> orderItems) {
        this.orderItems = orderItems;
    }

    @Override
    public final boolean equals(Object object) {
        if (object == this) {
            return true;
        }
        return (object instanceof OrderItemUpdate that)
                && Objects.equals(that.orderItems, this.orderItems);
    }

    @Override
    public final int hashCode() {
        return Objects.hash(orderItems);
    }

    @Override
    public String toString() {
        return "OrderItemUpdate [" +
                "orderItems=" + orderItems +
                ']';
    }
}

