/*
 * Order Service G09
 * API designed by team G09 for the HS24 SWDA course at HSLU
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ch.hslu.swda.common.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.micronaut.core.annotation.Introspected;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Schema for updating a customer of an order
 */
@Schema(name = "OrderCustomerUpdate", description = "Schema for updating a customer of an order")
@JsonPropertyOrder({
        OrderCustomerUpdate.JSON_PROPERTY_CUSTOMER,
})

@Introspected
public class OrderCustomerUpdate {

    public static final String JSON_PROPERTY_CUSTOMER = "customer";
    private Customer customer = null;

    public OrderCustomerUpdate(Customer customer) {
        this.customer = customer;
    }

    public OrderCustomerUpdate() {
    }

    public OrderCustomerUpdate customer(Customer customer) {
        this.customer = customer;
        return this;
    }

    @Schema(name = "customer", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_CUSTOMER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Customer getCustomer() {
        return this.customer;
    }

    @JsonProperty(JSON_PROPERTY_CUSTOMER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    @Override
    public final boolean equals(Object object) {
        if (object == this) {
            return true;
        }
        return (object instanceof OrderCustomerUpdate that)
                && Objects.equals(that.customer, this.customer);
    }

    @Override
    public final int hashCode() {
        return Objects.hash(this.customer);
    }

    @Override
    public String toString() {
        return "OrderCustomerUpdate [" +
                "customer=" + this.customer +
                ']';
    }
}

