/*
 * Order Service G09
 * API designed by team G09 for the HS24 SWDA course at HSLU
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ch.hslu.swda.common.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.micronaut.core.annotation.Introspected;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Schema for updating the status of an order
 */
@Schema(name = "OrderStatusUpdate", description = "Schema for updating the status of an order")
@JsonPropertyOrder({
        OrderStatusUpdate.JSON_PROPERTY_ORDER_STATUS,
})

@Introspected
public class OrderStatusUpdate {

    public static final String JSON_PROPERTY_ORDER_STATUS = "status";
    private Order.StatusEnum status = null;

    public OrderStatusUpdate(Order.StatusEnum status) {
        this.status = status;
    }

    public OrderStatusUpdate() {
    }

    public OrderStatusUpdate status(Order.StatusEnum status) {
        this.status = status;
        return this;
    }

    @Schema(name = "status", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_ORDER_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Order.StatusEnum getStatus() {
        return this.status;
    }

    @JsonProperty(JSON_PROPERTY_ORDER_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStatus(Order.StatusEnum status) {
        this.status = status;
    }

    @Override
    public final boolean equals(Object object) {
        if (object == this) {
            return true;
        }
        return (object instanceof OrderStatusUpdate that)
                && Objects.equals(that.status, this.status);
    }

    @Override
    public final int hashCode() {
        return Objects.hash(this.status);
    }

    @Override
    public String toString() {
        return "OrderStatusUpdate [" +
                "status=" + this.status +
                ']';
    }
}

