/*
 * Order Service G09
 * API designed by team G09 for the HS24 SWDA course at HSLU
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ch.hslu.swda.common.entities;

import com.fasterxml.jackson.annotation.*;
import io.micronaut.core.annotation.Introspected;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * ReplenishmentOrder
 */
@JsonPropertyOrder({
  ReplenishmentOrder.JSON_PROPERTY_TRACKING_ID,
  ReplenishmentOrder.JSON_PROPERTY_DELIVERY_DATE,
  ReplenishmentOrder.JSON_PROPERTY_STATUS,
  ReplenishmentOrder.JSON_PROPERTY_PRODUCT,
  ReplenishmentOrder.JSON_PROPERTY_QUANTITY
})
@JsonTypeName("ReplenishmentOrder")
@Introspected
public class ReplenishmentOrder {
    public static final String JSON_PROPERTY_TRACKING_ID = "trackingId";
    private UUID trackingId;

    public static final String JSON_PROPERTY_DELIVERY_DATE = "deliveryDate";
    private LocalDate deliveryDate;

    /**
     * Gets or Sets status
     */
    public enum StatusEnum {
        PENDING("PENDING"),
        CONFIRMED("CONFIRMED"),
        DONE("DONE");

        private String value;

        StatusEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static StatusEnum fromValue(String value) {
            for (StatusEnum b : StatusEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public static final String JSON_PROPERTY_STATUS = "status";
    private StatusEnum status;

    public static final String JSON_PROPERTY_PRODUCT = "product";
    private Product product;

    public static final String JSON_PROPERTY_QUANTITY = "quantity";
    private int quantity;

    private ReplenishmentReservation reservation;

    public ReplenishmentOrder(UUID trackingId, LocalDate deliveryDate, StatusEnum status, Product product, int quantity, ReplenishmentReservation reservation) {
        this.trackingId = trackingId;
        this.deliveryDate = deliveryDate;
        this.status = status;
        this.product = product;
        this.quantity = quantity;
        this.reservation = reservation;
    }

    public ReplenishmentOrder trackingId(UUID trackingId) {
        this.trackingId = trackingId;
        return this;
    }

    /**
     * Get id
     * @return id
     */
    @NotNull
    @Schema(name = "trackingId", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_TRACKING_ID)
    public UUID getTrackingId() {
        return trackingId;
    }

    @JsonProperty(JSON_PROPERTY_TRACKING_ID)
    public void setTrackingId(UUID trackingId) {
        this.trackingId = trackingId;
    }

    public ReplenishmentOrder deliveryDate(LocalDate deliveryDate) {
        this.deliveryDate = deliveryDate;
        return this;
    }

    /**
     * Get dateTime
     * @return dateTime
     */
    @NotNull
    @Schema(name = "deliveryDate", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_DELIVERY_DATE)
    @JsonFormat(pattern = "yyyy-MM-dd")
    public LocalDate getDeliveryDate() {
        return deliveryDate;
    }

    @JsonProperty(JSON_PROPERTY_DELIVERY_DATE)
    @JsonFormat(pattern = "yyyy-MM-dd")
    public void setDeliveryDate(LocalDate deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    public ReplenishmentOrder status(StatusEnum status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     * @return status
     */
    @NotNull
    @Schema(name = "status", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_STATUS)
    public StatusEnum getStatus() {
        return status;
    }

    @JsonProperty(JSON_PROPERTY_STATUS)
    public void setStatus(StatusEnum status) {
        this.status = status;
    }

    public ReplenishmentOrder product(Product product) {
        this.product = product;
        return this;
    }

    /**
     * Get product
     * @return product
     */
    @NotNull
    @Schema(name = "product", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_PRODUCT)
    public Product getProduct() {
        return product;
    }

    @JsonProperty(JSON_PROPERTY_PRODUCT)
    public void setProduct(Product product) {
        this.product = product;
    }

    public ReplenishmentOrder quantity(int quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Get quantity
     * @return quantity
     */
    @NotNull
    @Schema(name = "quantity", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_QUANTITY)
    public int getQuantity() {
        return quantity;
    }

    @JsonProperty(JSON_PROPERTY_QUANTITY)
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @JsonIgnore
    public ReplenishmentReservation getReservation() {
        return reservation;
    }

    @JsonIgnore
    public void setReservation(ReplenishmentReservation reservation) {
        this.reservation = reservation;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ReplenishmentOrder that)) return false;
        return quantity == that.quantity && Objects.equals(trackingId, that.trackingId) && Objects.equals(deliveryDate, that.deliveryDate) && status == that.status && Objects.equals(product, that.product);
    }

    @Override
    public int hashCode() {
        return Objects.hash(trackingId, deliveryDate, status, product, quantity);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ReplenishmentOrder {\n");
        sb.append("    trackingId: ").append(toIndentedString(trackingId)).append("\n");
        sb.append("    deliveryDate: ").append(toIndentedString(deliveryDate)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    product: ").append(toIndentedString(product)).append("\n");
        sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
