/*
 * Order Service G09
 * API designed by team G09 for the HS24 SWDA course at HSLU
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ch.hslu.swda.common.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.micronaut.core.annotation.Introspected;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import java.util.Objects;
import java.util.UUID;

/**
 * Shipment
 */
@JsonPropertyOrder({
  Shipment.JSON_PROPERTY_ID,
  Shipment.JSON_PROPERTY_CUSTOMER_ORDER
})
@JsonTypeName("Shipment")
@Introspected
public class Shipment {
    public static final String JSON_PROPERTY_ID = "id";
    private UUID id;

    public static final String JSON_PROPERTY_CUSTOMER_ORDER = "customerOrder";
    private CustomerOrder customerOrder;

    public Shipment(UUID id, CustomerOrder customerOrder) {
        this.id = id;
        this.customerOrder = customerOrder;
    }

    public Shipment id(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     */
    @NotNull
    @Schema(name = "id", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UUID getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setId(UUID id) {
        this.id = id;
    }

    public Shipment customerOrder(CustomerOrder customerOrder) {
        this.customerOrder = customerOrder;
        return this;
    }

    /**
     * Get customerOrder
     * @return customerOrder
     */
    @Valid
    @NotNull
    @Schema(name = "customerOrder", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_CUSTOMER_ORDER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public CustomerOrder getCustomerOrder() {
        return customerOrder;
    }

    @JsonProperty(JSON_PROPERTY_CUSTOMER_ORDER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setCustomerOrder(CustomerOrder customerOrder) {
        this.customerOrder = customerOrder;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Shipment shipment = (Shipment) o;
        return Objects.equals(this.id, shipment.id) &&
            Objects.equals(this.customerOrder, shipment.customerOrder);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, customerOrder);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Shipment {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    customerOrder: ").append(toIndentedString(customerOrder)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

