/*
 * Order Service G09
 * API designed by team G09 for the HS24 SWDA course at HSLU
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ch.hslu.swda.common.entities;

import java.util.Objects;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.*;
import java.time.OffsetDateTime;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import io.micronaut.core.annotation.*;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Shipment
 */
@JsonPropertyOrder({
        Shipment.JSON_PROPERTY_ID,
        Shipment.JSON_PROPERTY_CUSTOMER_ORDER,
        Shipment.JSON_PROPERTY_DEPARTURE,
        Shipment.JSON_PROPERTY_ESTIMATED_ARRIVAL
})
@JsonTypeName("Shipment")
@Introspected
public class Shipment {
    public static final String JSON_PROPERTY_ID = "id";
    private UUID id;

    public static final String JSON_PROPERTY_CUSTOMER_ORDER = "customerOrder";
    private CustomerOrder customerOrder;

    public static final String JSON_PROPERTY_DEPARTURE = "departure";
    private OffsetDateTime departure;

    public static final String JSON_PROPERTY_ESTIMATED_ARRIVAL = "estimatedArrival";
    private OffsetDateTime estimatedArrival;

    public Shipment(UUID id, CustomerOrder customerOrder) {
        this.id = id;
        this.customerOrder = customerOrder;
    }

    public Shipment() {}

    public Shipment id(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     */
    @NotNull
    @Schema(name = "id", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UUID getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setId(UUID id) {
        this.id = id;
    }

    public Shipment customerOrder(CustomerOrder customerOrder) {
        this.customerOrder = customerOrder;
        return this;
    }

    /**
     * Get customerOrder
     * @return customerOrder
     */
    @Valid
    @NotNull
    @Schema(name = "customerOrder", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_CUSTOMER_ORDER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public CustomerOrder getCustomerOrder() {
        return customerOrder;
    }

    @JsonProperty(JSON_PROPERTY_CUSTOMER_ORDER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setCustomerOrder(CustomerOrder customerOrder) {
        this.customerOrder = customerOrder;
    }

    public Shipment departure(OffsetDateTime departure) {
        this.departure = departure;
        return this;
    }

    /**
     * The date and time when the shipment departs
     * @return departure
     */
    @Nullable
    @Schema(name = "departure", description = "The date and time when the shipment departs", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_DEPARTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public OffsetDateTime getDeparture() {
        return departure;
    }

    @JsonProperty(JSON_PROPERTY_DEPARTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public void setDeparture(OffsetDateTime departure) {
        this.departure = departure;
    }

    public Shipment estimatedArrival(OffsetDateTime estimatedArrival) {
        this.estimatedArrival = estimatedArrival;
        return this;
    }

    /**
     * The estimated date and time of arrival for the shipment
     * @return estimatedArrival
     */
    @Nullable
    @Schema(name = "estimatedArrival", description = "The estimated date and time of arrival for the shipment", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_ESTIMATED_ARRIVAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public OffsetDateTime getEstimatedArrival() {
        return estimatedArrival;
    }

    @JsonProperty(JSON_PROPERTY_ESTIMATED_ARRIVAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public void setEstimatedArrival(OffsetDateTime estimatedArrival) {
        this.estimatedArrival = estimatedArrival;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Shipment shipment = (Shipment) o;
        return Objects.equals(this.id, shipment.id) &&
                Objects.equals(this.customerOrder, shipment.customerOrder) &&
                Objects.equals(this.departure, shipment.departure) &&
                Objects.equals(this.estimatedArrival, shipment.estimatedArrival);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, customerOrder, departure, estimatedArrival);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Shipment {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    customerOrder: ").append(toIndentedString(customerOrder)).append("\n");
        sb.append("    departure: ").append(toIndentedString(departure)).append("\n");
        sb.append("    estimatedArrival: ").append(toIndentedString(estimatedArrival)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
