/*
 * Order Service G09
 * API designed by team G09 for the HS24 SWDA course at HSLU
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ch.hslu.swda.common.entities;

import com.fasterxml.jackson.annotation.*;
import io.micronaut.core.annotation.Introspected;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import org.bson.types.ObjectId;

import java.time.LocalDate;
import java.util.Objects;
import java.util.UUID;

/**
 * ReplenishmentOrder
 */
@JsonPropertyOrder({
  SimpleReplenishmentOrder.JSON_PROPERTY_TRACKING_ID,
  SimpleReplenishmentOrder.JSON_PROPERTY_DELIVERY_DATE,
  SimpleReplenishmentOrder.JSON_PROPERTY_STATUS,
  SimpleReplenishmentOrder.JSON_PROPERTY_PRODUCT_ID,
  SimpleReplenishmentOrder.JSON_PROPERTY_QUANTITY
})
@JsonTypeName("ReplenishmentOrder")
@Introspected
public class SimpleReplenishmentOrder {
    public static final String JSON_PROPERTY_TRACKING_ID = "trackingId";
    private UUID trackingId;

    public static final String JSON_PROPERTY_DELIVERY_DATE = "deliveryDate";
    private LocalDate deliveryDate;

    public static final String JSON_PROPERTY_STATUS = "status";
    private ReplenishmentOrder.StatusEnum status;

    public static final String JSON_PROPERTY_PRODUCT_ID = "productId";
    private int productId;

    public static final String JSON_PROPERTY_QUANTITY = "quantity";
    private int quantity;

    private ObjectId id;

    public SimpleReplenishmentOrder(UUID trackingId, LocalDate deliveryDate, ReplenishmentOrder.StatusEnum status, int productId, int quantity, ObjectId id) {
        this.trackingId = trackingId;
        this.deliveryDate = deliveryDate;
        this.status = status;
        this.productId = productId;
        this.quantity = quantity;
        this.id = id;
    }

    public SimpleReplenishmentOrder(UUID trackingId, LocalDate deliveryDate, ReplenishmentOrder.StatusEnum status, int productId, int quantity) {
        this.trackingId = trackingId;
        this.deliveryDate = deliveryDate;
        this.status = status;
        this.productId = productId;
        this.quantity = quantity;
        this.id = new ObjectId();
    }

    public SimpleReplenishmentOrder() {}

    public SimpleReplenishmentOrder(ReplenishmentOrder order) {
        this.trackingId = order.getTrackingId();
        this.deliveryDate = order.getDeliveryDate();
        this.status = order.getStatus();
        this.productId = order.getProduct().getId();
        this.quantity = order.getQuantity();
    }

    public SimpleReplenishmentOrder trackingId(UUID trackingId) {
        this.trackingId = trackingId;
        return this;
    }

    /**
     * Get id
     * @return id
     */
    @NotNull
    @Schema(name = "trackingId", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_TRACKING_ID)
    public UUID getTrackingId() {
        return trackingId;
    }

    @JsonProperty(JSON_PROPERTY_TRACKING_ID)
    public void setTrackingId(UUID trackingId) {
        this.trackingId = trackingId;
    }

    public SimpleReplenishmentOrder deliveryDate(LocalDate deliveryDate) {
        this.deliveryDate = deliveryDate;
        return this;
    }

    /**
     * Get dateTime
     * @return dateTime
     */
    @NotNull
    @Schema(name = "deliveryDate", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_DELIVERY_DATE)
    @JsonFormat(pattern = "yyyy-MM-dd")
    public LocalDate getDeliveryDate() {
        return deliveryDate;
    }

    @JsonProperty(JSON_PROPERTY_DELIVERY_DATE)
    @JsonFormat(pattern = "yyyy-MM-dd")
    public void setDeliveryDate(LocalDate deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    public SimpleReplenishmentOrder status(ReplenishmentOrder.StatusEnum status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     * @return status
     */
    @NotNull
    @Schema(name = "status", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_STATUS)
    public ReplenishmentOrder.StatusEnum getStatus() {
        return status;
    }

    @JsonProperty(JSON_PROPERTY_STATUS)
    public void setStatus(ReplenishmentOrder.StatusEnum status) {
        this.status = status;
    }

    public SimpleReplenishmentOrder productId(int productId) {
        this.productId = productId;
        return this;
    }

    /**
     * Get productId
     * @return productId
     */
    @NotNull
    @Schema(name = "productId", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
    public int getProductId() {
        return productId;
    }

    @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
    public void setProductId(int productId) {
        this.productId = productId;
    }

    public SimpleReplenishmentOrder quantity(int quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Get quantity
     * @return quantity
     */
    @NotNull
    @Schema(name = "quantity", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_QUANTITY)
    public int getQuantity() {
        return quantity;
    }

    @JsonProperty(JSON_PROPERTY_QUANTITY)
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @JsonIgnore
    public ObjectId getId() {
        return id;
    }

    public void setId(ObjectId id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SimpleReplenishmentOrder that)) return false;
        return quantity == that.quantity && Objects.equals(trackingId, that.trackingId) && Objects.equals(deliveryDate, that.deliveryDate) && status == that.status && productId == that.productId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(trackingId, deliveryDate, status, productId, quantity);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ReplenishmentOrder {\n");
        sb.append("    trackingId: ").append(toIndentedString(trackingId)).append("\n");
        sb.append("    deliveryDate: ").append(toIndentedString(deliveryDate)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
        sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
